### ISSUE TITLE
SQLite Inspector

### ISSUE THREAD

**Issue by Zinidinio** [MrAGi/SQLiteInspector#4]
Why is there like 10 programs. Wheres the actual SQLite inspector download file. There's all this other stuff but wheres the main thing I need. Please reply quickly I've spent an hour and no RESULT!!!

**Comment by Zinidinio** [comment]
Hello!!!

**Comment by MrAGi** [comment]
You can find the releases here:

https://github.com/MrAGi/SQLiteInspector/releases

I don’t support this anymore and if it doesn’t work for you I am sorry but you will need to find another program that does the same thing.
